#!/usr/bin/env bash

#put this script to /usr/local/sbin to call easily
cat $0
read -p "Are you going to execute the above script? Press any key to continue." -n1 -s
if [[ $1 == "over" ]]
then
  #nvidia-settings -a [gpu:0]/GPUPowerMizerMode=1
  nvidia-settings -a GPUGraphicsClockOffsetAllPerformanceLevels=110
  nvidia-settings -a GPUMemoryTransferRateOffsetAllPerformanceLevels=500
elif [[ $1 == "drop" ]]
then
  #nvidia-settings -a [gpu:0]/GPUPowerMizerMode=1
  nvidia-settings -a GPUGraphicsClockOffsetAllPerformanceLevels=0
  nvidia-settings -a GPUMemoryTransferRateOffsetAllPerformanceLevels=0
else
  echo ""
  echo "Doing nothing."
  echo ""
fi
if [[ $1 == "over" ]] || [[ $1 == "drop" ]]
then
  echo ""
  echo "### Result ###"
  echo ""
  nvidia-settings -q GPUGraphicsClockOffsetAllPerformanceLevels
  nvidia-settings -q GPUMemoryTransferRateOffsetAllPerformanceLevels
fi
read -p "Done, ready to monitor temps. Press any key to continue." -n1 -s
echo ""
echo ""
watch -n 2 nvidia-smi

