#!/bin/bash
yellow='\033[1;33m'
end_color='\033[0m'
echo -e "${yellow}# Connecting to Pi-hole LXD #${end_color}"
lxc exec pihole -- /usr/bin/apt update
lxc exec pihole -- /usr/bin/apt upgrade -y
lxc exec pihole -- /usr/bin/apt autoremove -y
echo -e "${yellow}# Connecting to Apps LXD #${end_color}"
lxc start apps || true
sleep 6
lxc exec apps -- /usr/bin/apt update
lxc exec apps -- /usr/bin/apt upgrade -y
lxc exec apps -- /usr/bin/apt autoremove -y
echo -e "${yellow}# Connecting to Nextcloud AWS #${end_color}"
ssh -t username@server1 "sudo apt upgrade -y && sudo apt autoremove -y"
echo -e "${yellow}# Connecting to Pi-hole AWS #${end_color}"
ssh -t username@server2 "sudo apt upgrade -y && sudo apt autoremove -y"
