#!/usr/bin/env bash

set -e
#make readonly snapshot of live data
sudo btrfs subvolume snapshot -r /mnt/wd_green/Data /mnt/wd_green/data_backups/backup_new
#prepare send - receive script, it will snapshot the difference between new and reference
echo "#!/usr/bin/env bash
btrfs send -p /mnt/wd_green/data_backups/backup_reference /mnt/wd_green/data_backups/backup_new | btrfs receive /mnt/wd_green/data_backups/incremental" | sudo tee /opt/btrfs_send
#execute send - receive script
sudo /opt/btrfs_send
#rename the difference: include date
sudo mv /mnt/wd_green/data_backups/incremental/backup_new /mnt/wd_green/data_backups/incremental/backup_$(date +%Y-%m-%d)
#delete the (now old) reference
sudo btrfs subvolume delete /mnt/wd_green/data_backups/backup_reference
#rename the new snapshot into (future) reference
sudo mv /mnt/wd_green/data_backups/backup_new /mnt/wd_green/data_backups/backup_reference
