#!/usr/bin/env bash

if [[ "$1" -lt "1" ]]
then
	echo "Wrong parameter. Timer needs one number above zero."
fi
target=$(("$1" + 1))
i=1
while [[ "$i" -lt "$target" ]]
do
	sleep 1
	echo "$i"
	i=$(("$i" + 1))
done
mpv --msg-level=all=no /usr/share/sounds/freedesktop/stereo/complete.oga
